require: rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/* 
    - config/**/*
    - db/**/*
    - bin/**/*
    - Gemfile