
default: &default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: DebtsPayPlan_development

test:
  <<: *default
  database: DebtsPayPlan_test

production:
  <<: *default
  database: DebtsPayPlan_production
  username: DebtsPayPlan
  password: <%= ENV['DEBTSPAYPLAN_DATABASE_PASSWORD'] %>
